-- MySQL Script generated by MySQL Workbench
-- Wed May 11 16:00:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sparta_realDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sparta_realDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sparta_realDB` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema sparta_realDB2
-- -----------------------------------------------------
USE `sparta_realDB` ;

-- -----------------------------------------------------
-- Table `sparta_realDB`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparta_realDB`.`User` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `userEmail` VARCHAR(200) NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `userImage` VARCHAR(3000) NULL,
  `tradeCount` INT NULL,
  `point` INT NULL,
  `createdAt` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`userId`, `userEmail`, `userName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparta_realDB`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparta_realDB`.`Post` (
  `postId` INT NOT NULL AUTO_INCREMENT,
  `User_userId` INT NULL,
  `title` VARCHAR(200) NULL,
  `content` VARCHAR(2000) NULL,
  `writer` VARCHAR(100) NULL,
  `price` INT NULL,
  `headCount` INT NULL,
  `category` VARCHAR(2000) NULL,
  `isDone` TINYINT NULL,
  `image` VARCHAR(5000) NULL,
  `lat` VARCHAR(2000) NULL,
  `lng` VARCHAR(2000) NULL,
  `address` VARCHAR(2000) NULL,
  `createdAt` DATETIME NULL DEFAULT now(),
  `endTime` DATETIME NULL,
  PRIMARY KEY (`postId`),
  INDEX `fk_Post_User1_idx` (`User_userId` ASC) VISIBLE,
  CONSTRAINT `fk_Post_User1`
    FOREIGN KEY (`User_userId`)
    REFERENCES `sparta_realDB`.`User` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparta_realDB`.`Chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparta_realDB`.`Chat` (
  `chatId` INT NOT NULL AUTO_INCREMENT,
  `Post_postId` INT NULL,
  `chat` VARCHAR(2000) NULL,
  `createdAt` DATETIME NULL DEFAULT now(),
  `Room_roomId` INT NULL,
  `User_userId` INT NOT NULL,
  `User_userEmail` VARCHAR(200) NOT NULL,
  `User_userName` VARCHAR(45) NOT NULL,
  `userImage` VARCHAR(3000) NULL,
  PRIMARY KEY (`chatId`),
  INDEX `fk_Chat_Post1_idx` (`Post_postId` ASC) VISIBLE,
  INDEX `fk_Chat_User1_idx` (`User_userId` ASC, `User_userEmail` ASC, `User_userName` ASC) VISIBLE,
  CONSTRAINT `fk_Chat_Post1`
    FOREIGN KEY (`Post_postId`)
    REFERENCES `sparta_realDB`.`Post` (`postId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chat_User1`
    FOREIGN KEY (`User_userId` , `User_userEmail` , `User_userName`)
    REFERENCES `sparta_realDB`.`User` (`userId` , `userEmail` , `userName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparta_realDB`.`Like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparta_realDB`.`Like` (
  `likeId` INT NOT NULL AUTO_INCREMENT,
  `createdAt` DATETIME NULL DEFAULT now(),
  `Post_postId` INT NOT NULL,
  `User_userId` INT NOT NULL,
  PRIMARY KEY (`likeId`, `Post_postId`),
  INDEX `fk_Like_Post1_idx` (`Post_postId` ASC) VISIBLE,
  INDEX `fk_Like_User1_idx` (`User_userId` ASC) VISIBLE,
  CONSTRAINT `fk_Like_Post1`
    FOREIGN KEY (`Post_postId`)
    REFERENCES `sparta_realDB`.`Post` (`postId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Like_User1`
    FOREIGN KEY (`User_userId`)
    REFERENCES `sparta_realDB`.`User` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparta_realDB`.`AuthNum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparta_realDB`.`AuthNum` (
  `authNumId` INT NOT NULL AUTO_INCREMENT,
  `authNum` VARCHAR(45) NULL,
  `createdAt` DATETIME NULL DEFAULT now(),
  `userEmail` VARCHAR(200) NULL,
  PRIMARY KEY (`authNumId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparta_realDB`.`JoinPost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparta_realDB`.`JoinPost` (
  `joinId` INT NOT NULL AUTO_INCREMENT,
  `createdAt` DATETIME NULL DEFAULT now(),
  `isPick` TINYINT NULL,
  `userImage` VARCHAR(3000) NULL,
  `Post_postId` INT NULL,
  `User_userId` INT NOT NULL,
  `User_userEmail` VARCHAR(200) NOT NULL,
  `User_userName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`joinId`),
  INDEX `fk_JoinPost_Post1_idx` (`Post_postId` ASC) VISIBLE,
  INDEX `fk_JoinPost_User1_idx` (`User_userId` ASC, `User_userEmail` ASC, `User_userName` ASC) VISIBLE,
  CONSTRAINT `fk_JoinPost_Post1`
    FOREIGN KEY (`Post_postId`)
    REFERENCES `sparta_realDB`.`Post` (`postId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JoinPost_User1`
    FOREIGN KEY (`User_userId` , `User_userEmail` , `User_userName`)
    REFERENCES `sparta_realDB`.`User` (`userId` , `userEmail` , `userName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparta_realDB`.`Alaram`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparta_realDB`.`Alaram` (
  `alaramId` INT NOT NULL AUTO_INCREMENT,
  `msg` VARCHAR(500) NULL,
  `createdAt` DATETIME NULL DEFAULT now(),
  `userImage` VARCHAR(3000) NULL,
  `ischecked` TINYINT NULL,
  `User_userId` INT NOT NULL,
  `User_userEmail` VARCHAR(200) NOT NULL,
  `User_userName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`alaramId`),
  INDEX `fk_Alaram_User1_idx` (`User_userId` ASC, `User_userEmail` ASC, `User_userName` ASC) VISIBLE,
  CONSTRAINT `fk_Alaram_User1`
    FOREIGN KEY (`User_userId` , `User_userEmail` , `User_userName`)
    REFERENCES `sparta_realDB`.`User` (`userId` , `userEmail` , `userName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
